import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Grid1 from "@/components/Grid";
import Appbar from "@/components/Appbar";
import Box1 from "@/components/Box";
import HookForm from "@/components/HookForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn Mui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <main className={styles.main}>
      {/* <Box1></Box1>
      <Appbar></Appbar>
      <Grid1></Grid1> */}
      <HookForm></HookForm>


      </main>
    </>
  );
}
